/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedProductCategoriesIndexRouteImport } from './routes/_authenticated/product-categories/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as AuthenticatedCashBankIndexRouteImport } from './routes/_authenticated/cash-bank/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedCashBankSpendRouteImport } from './routes/_authenticated/cash-bank/spend'
import { Route as AuthenticatedCashBankReceiveRouteImport } from './routes/_authenticated/cash-bank/receive'
import { Route as AuthenticatedCashBankEditRouteImport } from './routes/_authenticated/cash-bank/edit'
import { Route as AuthenticatedCashBankDetailRouteImport } from './routes/_authenticated/cash-bank/detail'
import { Route as AuthenticatedCashBankAccountNameRouteImport } from './routes/_authenticated/cash-bank/$accountName'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsUnitsIndexRouteImport } from './routes/_authenticated/settings/units/index'
import { Route as AuthenticatedSettingsTaxesIndexRouteImport } from './routes/_authenticated/settings/taxes/index'
import { Route as AuthenticatedSettingsTagsIndexRouteImport } from './routes/_authenticated/settings/tags/index'
import { Route as AuthenticatedSettingsSubscriptionIndexRouteImport } from './routes/_authenticated/settings/subscription/index'
import { Route as AuthenticatedSettingsProfileIndexRouteImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthenticatedSettingsPaymentTermsIndexRouteImport } from './routes/_authenticated/settings/payment-terms/index'
import { Route as AuthenticatedSettingsCompanyIndexRouteImport } from './routes/_authenticated/settings/company/index'
import { Route as AuthenticatedSettingsCompanyRolesIndexRouteImport } from './routes/_authenticated/settings/company-roles/index'
import { Route as AuthenticatedSettingsAutoSequencingIndexRouteImport } from './routes/_authenticated/settings/auto-sequencing/index'
import { Route as AuthenticatedSalesOverviewIndexRouteImport } from './routes/_authenticated/sales/overview/index'
import { Route as AuthenticatedSalesInvoicesIndexRouteImport } from './routes/_authenticated/sales/invoices/index'
import { Route as AuthenticatedReportsProfitLossIndexRouteImport } from './routes/_authenticated/reports/profit-loss/index'
import { Route as AuthenticatedReportsBalanceSheetIndexRouteImport } from './routes/_authenticated/reports/balance-sheet/index'
import { Route as AuthenticatedPurchasesOverviewIndexRouteImport } from './routes/_authenticated/purchases/overview/index'
import { Route as AuthenticatedPurchasesInvoicesIndexRouteImport } from './routes/_authenticated/purchases/invoices/index'
import { Route as AuthenticatedProductsEditIndexRouteImport } from './routes/_authenticated/products/edit/index'
import { Route as AuthenticatedProductsAddIndexRouteImport } from './routes/_authenticated/products/add/index'
import { Route as AuthenticatedExpensesEditIndexRouteImport } from './routes/_authenticated/expenses/edit/index'
import { Route as AuthenticatedExpensesDetailIndexRouteImport } from './routes/_authenticated/expenses/detail/index'
import { Route as AuthenticatedExpensesAddIndexRouteImport } from './routes/_authenticated/expenses/add/index'
import { Route as AuthenticatedAdminTransactionTypesIndexRouteImport } from './routes/_authenticated/admin/transaction-types/index'
import { Route as AuthenticatedAdminSubscriptionsIndexRouteImport } from './routes/_authenticated/admin/subscriptions/index'
import { Route as AuthenticatedAdminPlansIndexRouteImport } from './routes/_authenticated/admin/plans/index'
import { Route as AuthenticatedAdminPermissionsIndexRouteImport } from './routes/_authenticated/admin/permissions/index'
import { Route as AuthenticatedAdminMenusIndexRouteImport } from './routes/_authenticated/admin/menus/index'
import { Route as AuthenticatedAdminMenuCategoriesIndexRouteImport } from './routes/_authenticated/admin/menu-categories/index'
import { Route as AuthenticatedAdminAccountCategoriesIndexRouteImport } from './routes/_authenticated/admin/account-categories/index'
import { Route as AuthenticatedSettingsCompanyRolesEditIndexRouteImport } from './routes/_authenticated/settings/company-roles/edit/index'
import { Route as AuthenticatedSettingsCompanyRolesAddIndexRouteImport } from './routes/_authenticated/settings/company-roles/add/index'
import { Route as AuthenticatedSalesInvoicesEditIndexRouteImport } from './routes/_authenticated/sales/invoices/edit/index'
import { Route as AuthenticatedSalesInvoicesDetailIndexRouteImport } from './routes/_authenticated/sales/invoices/detail/index'
import { Route as AuthenticatedSalesInvoicesAddIndexRouteImport } from './routes/_authenticated/sales/invoices/add/index'
import { Route as AuthenticatedPurchasesInvoicesEditIndexRouteImport } from './routes/_authenticated/purchases/invoices/edit/index'
import { Route as AuthenticatedPurchasesInvoicesDetailIndexRouteImport } from './routes/_authenticated/purchases/invoices/detail/index'
import { Route as AuthenticatedPurchasesInvoicesAddIndexRouteImport } from './routes/_authenticated/purchases/invoices/add/index'
import { Route as AuthenticatedAdminPlansPlanIdPermissionsIndexRouteImport } from './routes/_authenticated/admin/plans/$planId/permissions/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductCategoriesIndexRoute =
  AuthenticatedProductCategoriesIndexRouteImport.update({
    id: '/product-categories/',
    path: '/product-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankIndexRoute =
  AuthenticatedCashBankIndexRouteImport.update({
    id: '/cash-bank/',
    path: '/cash-bank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankSpendRoute =
  AuthenticatedCashBankSpendRouteImport.update({
    id: '/cash-bank/spend',
    path: '/cash-bank/spend',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankReceiveRoute =
  AuthenticatedCashBankReceiveRouteImport.update({
    id: '/cash-bank/receive',
    path: '/cash-bank/receive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankEditRoute =
  AuthenticatedCashBankEditRouteImport.update({
    id: '/cash-bank/edit',
    path: '/cash-bank/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankDetailRoute =
  AuthenticatedCashBankDetailRouteImport.update({
    id: '/cash-bank/detail',
    path: '/cash-bank/detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashBankAccountNameRoute =
  AuthenticatedCashBankAccountNameRouteImport.update({
    id: '/cash-bank/$accountName',
    path: '/cash-bank/$accountName',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/settings/users/',
    path: '/settings/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUnitsIndexRoute =
  AuthenticatedSettingsUnitsIndexRouteImport.update({
    id: '/settings/units/',
    path: '/settings/units/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTaxesIndexRoute =
  AuthenticatedSettingsTaxesIndexRouteImport.update({
    id: '/settings/taxes/',
    path: '/settings/taxes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTagsIndexRoute =
  AuthenticatedSettingsTagsIndexRouteImport.update({
    id: '/settings/tags/',
    path: '/settings/tags/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSubscriptionIndexRoute =
  AuthenticatedSettingsSubscriptionIndexRouteImport.update({
    id: '/settings/subscription/',
    path: '/settings/subscription/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexRouteImport.update({
    id: '/settings/profile/',
    path: '/settings/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPaymentTermsIndexRoute =
  AuthenticatedSettingsPaymentTermsIndexRouteImport.update({
    id: '/settings/payment-terms/',
    path: '/settings/payment-terms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyIndexRoute =
  AuthenticatedSettingsCompanyIndexRouteImport.update({
    id: '/settings/company/',
    path: '/settings/company/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRolesIndexRoute =
  AuthenticatedSettingsCompanyRolesIndexRouteImport.update({
    id: '/settings/company-roles/',
    path: '/settings/company-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAutoSequencingIndexRoute =
  AuthenticatedSettingsAutoSequencingIndexRouteImport.update({
    id: '/settings/auto-sequencing/',
    path: '/settings/auto-sequencing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOverviewIndexRoute =
  AuthenticatedSalesOverviewIndexRouteImport.update({
    id: '/sales/overview/',
    path: '/sales/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInvoicesIndexRoute =
  AuthenticatedSalesInvoicesIndexRouteImport.update({
    id: '/sales/invoices/',
    path: '/sales/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsProfitLossIndexRoute =
  AuthenticatedReportsProfitLossIndexRouteImport.update({
    id: '/reports/profit-loss/',
    path: '/reports/profit-loss/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsBalanceSheetIndexRoute =
  AuthenticatedReportsBalanceSheetIndexRouteImport.update({
    id: '/reports/balance-sheet/',
    path: '/reports/balance-sheet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesOverviewIndexRoute =
  AuthenticatedPurchasesOverviewIndexRouteImport.update({
    id: '/purchases/overview/',
    path: '/purchases/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesInvoicesIndexRoute =
  AuthenticatedPurchasesInvoicesIndexRouteImport.update({
    id: '/purchases/invoices/',
    path: '/purchases/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsEditIndexRoute =
  AuthenticatedProductsEditIndexRouteImport.update({
    id: '/products/edit/',
    path: '/products/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsAddIndexRoute =
  AuthenticatedProductsAddIndexRouteImport.update({
    id: '/products/add/',
    path: '/products/add/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesEditIndexRoute =
  AuthenticatedExpensesEditIndexRouteImport.update({
    id: '/expenses/edit/',
    path: '/expenses/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesDetailIndexRoute =
  AuthenticatedExpensesDetailIndexRouteImport.update({
    id: '/expenses/detail/',
    path: '/expenses/detail/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesAddIndexRoute =
  AuthenticatedExpensesAddIndexRouteImport.update({
    id: '/expenses/add/',
    path: '/expenses/add/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTransactionTypesIndexRoute =
  AuthenticatedAdminTransactionTypesIndexRouteImport.update({
    id: '/transaction-types/',
    path: '/transaction-types/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionsIndexRoute =
  AuthenticatedAdminSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansIndexRoute =
  AuthenticatedAdminPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsIndexRoute =
  AuthenticatedAdminPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMenusIndexRoute =
  AuthenticatedAdminMenusIndexRouteImport.update({
    id: '/menus/',
    path: '/menus/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMenuCategoriesIndexRoute =
  AuthenticatedAdminMenuCategoriesIndexRouteImport.update({
    id: '/menu-categories/',
    path: '/menu-categories/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountCategoriesIndexRoute =
  AuthenticatedAdminAccountCategoriesIndexRouteImport.update({
    id: '/account-categories/',
    path: '/account-categories/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRolesEditIndexRoute =
  AuthenticatedSettingsCompanyRolesEditIndexRouteImport.update({
    id: '/settings/company-roles/edit/',
    path: '/settings/company-roles/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRolesAddIndexRoute =
  AuthenticatedSettingsCompanyRolesAddIndexRouteImport.update({
    id: '/settings/company-roles/add/',
    path: '/settings/company-roles/add/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInvoicesEditIndexRoute =
  AuthenticatedSalesInvoicesEditIndexRouteImport.update({
    id: '/sales/invoices/edit/',
    path: '/sales/invoices/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInvoicesDetailIndexRoute =
  AuthenticatedSalesInvoicesDetailIndexRouteImport.update({
    id: '/sales/invoices/detail/',
    path: '/sales/invoices/detail/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInvoicesAddIndexRoute =
  AuthenticatedSalesInvoicesAddIndexRouteImport.update({
    id: '/sales/invoices/add/',
    path: '/sales/invoices/add/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesInvoicesEditIndexRoute =
  AuthenticatedPurchasesInvoicesEditIndexRouteImport.update({
    id: '/purchases/invoices/edit/',
    path: '/purchases/invoices/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesInvoicesDetailIndexRoute =
  AuthenticatedPurchasesInvoicesDetailIndexRouteImport.update({
    id: '/purchases/invoices/detail/',
    path: '/purchases/invoices/detail/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesInvoicesAddIndexRoute =
  AuthenticatedPurchasesInvoicesAddIndexRouteImport.update({
    id: '/purchases/invoices/add/',
    path: '/purchases/invoices/add/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlansPlanIdPermissionsIndexRoute =
  AuthenticatedAdminPlansPlanIdPermissionsIndexRouteImport.update({
    id: '/plans/$planId/permissions/',
    path: '/plans/$planId/permissions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/cash-bank/$accountName': typeof AuthenticatedCashBankAccountNameRoute
  '/cash-bank/detail': typeof AuthenticatedCashBankDetailRoute
  '/cash-bank/edit': typeof AuthenticatedCashBankEditRoute
  '/cash-bank/receive': typeof AuthenticatedCashBankReceiveRoute
  '/cash-bank/spend': typeof AuthenticatedCashBankSpendRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/cash-bank': typeof AuthenticatedCashBankIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/product-categories': typeof AuthenticatedProductCategoriesIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/account-categories': typeof AuthenticatedAdminAccountCategoriesIndexRoute
  '/admin/menu-categories': typeof AuthenticatedAdminMenuCategoriesIndexRoute
  '/admin/menus': typeof AuthenticatedAdminMenusIndexRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsIndexRoute
  '/admin/plans': typeof AuthenticatedAdminPlansIndexRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsIndexRoute
  '/admin/transaction-types': typeof AuthenticatedAdminTransactionTypesIndexRoute
  '/expenses/add': typeof AuthenticatedExpensesAddIndexRoute
  '/expenses/detail': typeof AuthenticatedExpensesDetailIndexRoute
  '/expenses/edit': typeof AuthenticatedExpensesEditIndexRoute
  '/products/add': typeof AuthenticatedProductsAddIndexRoute
  '/products/edit': typeof AuthenticatedProductsEditIndexRoute
  '/purchases/invoices': typeof AuthenticatedPurchasesInvoicesIndexRoute
  '/purchases/overview': typeof AuthenticatedPurchasesOverviewIndexRoute
  '/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetIndexRoute
  '/reports/profit-loss': typeof AuthenticatedReportsProfitLossIndexRoute
  '/sales/invoices': typeof AuthenticatedSalesInvoicesIndexRoute
  '/sales/overview': typeof AuthenticatedSalesOverviewIndexRoute
  '/settings/auto-sequencing': typeof AuthenticatedSettingsAutoSequencingIndexRoute
  '/settings/company-roles': typeof AuthenticatedSettingsCompanyRolesIndexRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyIndexRoute
  '/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/settings/subscription': typeof AuthenticatedSettingsSubscriptionIndexRoute
  '/settings/tags': typeof AuthenticatedSettingsTagsIndexRoute
  '/settings/taxes': typeof AuthenticatedSettingsTaxesIndexRoute
  '/settings/units': typeof AuthenticatedSettingsUnitsIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/purchases/invoices/add': typeof AuthenticatedPurchasesInvoicesAddIndexRoute
  '/purchases/invoices/detail': typeof AuthenticatedPurchasesInvoicesDetailIndexRoute
  '/purchases/invoices/edit': typeof AuthenticatedPurchasesInvoicesEditIndexRoute
  '/sales/invoices/add': typeof AuthenticatedSalesInvoicesAddIndexRoute
  '/sales/invoices/detail': typeof AuthenticatedSalesInvoicesDetailIndexRoute
  '/sales/invoices/edit': typeof AuthenticatedSalesInvoicesEditIndexRoute
  '/settings/company-roles/add': typeof AuthenticatedSettingsCompanyRolesAddIndexRoute
  '/settings/company-roles/edit': typeof AuthenticatedSettingsCompanyRolesEditIndexRoute
  '/admin/plans/$planId/permissions': typeof AuthenticatedAdminPlansPlanIdPermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/cash-bank/$accountName': typeof AuthenticatedCashBankAccountNameRoute
  '/cash-bank/detail': typeof AuthenticatedCashBankDetailRoute
  '/cash-bank/edit': typeof AuthenticatedCashBankEditRoute
  '/cash-bank/receive': typeof AuthenticatedCashBankReceiveRoute
  '/cash-bank/spend': typeof AuthenticatedCashBankSpendRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/cash-bank': typeof AuthenticatedCashBankIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/product-categories': typeof AuthenticatedProductCategoriesIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/account-categories': typeof AuthenticatedAdminAccountCategoriesIndexRoute
  '/admin/menu-categories': typeof AuthenticatedAdminMenuCategoriesIndexRoute
  '/admin/menus': typeof AuthenticatedAdminMenusIndexRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsIndexRoute
  '/admin/plans': typeof AuthenticatedAdminPlansIndexRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsIndexRoute
  '/admin/transaction-types': typeof AuthenticatedAdminTransactionTypesIndexRoute
  '/expenses/add': typeof AuthenticatedExpensesAddIndexRoute
  '/expenses/detail': typeof AuthenticatedExpensesDetailIndexRoute
  '/expenses/edit': typeof AuthenticatedExpensesEditIndexRoute
  '/products/add': typeof AuthenticatedProductsAddIndexRoute
  '/products/edit': typeof AuthenticatedProductsEditIndexRoute
  '/purchases/invoices': typeof AuthenticatedPurchasesInvoicesIndexRoute
  '/purchases/overview': typeof AuthenticatedPurchasesOverviewIndexRoute
  '/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetIndexRoute
  '/reports/profit-loss': typeof AuthenticatedReportsProfitLossIndexRoute
  '/sales/invoices': typeof AuthenticatedSalesInvoicesIndexRoute
  '/sales/overview': typeof AuthenticatedSalesOverviewIndexRoute
  '/settings/auto-sequencing': typeof AuthenticatedSettingsAutoSequencingIndexRoute
  '/settings/company-roles': typeof AuthenticatedSettingsCompanyRolesIndexRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyIndexRoute
  '/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/settings/subscription': typeof AuthenticatedSettingsSubscriptionIndexRoute
  '/settings/tags': typeof AuthenticatedSettingsTagsIndexRoute
  '/settings/taxes': typeof AuthenticatedSettingsTaxesIndexRoute
  '/settings/units': typeof AuthenticatedSettingsUnitsIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/purchases/invoices/add': typeof AuthenticatedPurchasesInvoicesAddIndexRoute
  '/purchases/invoices/detail': typeof AuthenticatedPurchasesInvoicesDetailIndexRoute
  '/purchases/invoices/edit': typeof AuthenticatedPurchasesInvoicesEditIndexRoute
  '/sales/invoices/add': typeof AuthenticatedSalesInvoicesAddIndexRoute
  '/sales/invoices/detail': typeof AuthenticatedSalesInvoicesDetailIndexRoute
  '/sales/invoices/edit': typeof AuthenticatedSalesInvoicesEditIndexRoute
  '/settings/company-roles/add': typeof AuthenticatedSettingsCompanyRolesAddIndexRoute
  '/settings/company-roles/edit': typeof AuthenticatedSettingsCompanyRolesEditIndexRoute
  '/admin/plans/$planId/permissions': typeof AuthenticatedAdminPlansPlanIdPermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cash-bank/$accountName': typeof AuthenticatedCashBankAccountNameRoute
  '/_authenticated/cash-bank/detail': typeof AuthenticatedCashBankDetailRoute
  '/_authenticated/cash-bank/edit': typeof AuthenticatedCashBankEditRoute
  '/_authenticated/cash-bank/receive': typeof AuthenticatedCashBankReceiveRoute
  '/_authenticated/cash-bank/spend': typeof AuthenticatedCashBankSpendRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/cash-bank/': typeof AuthenticatedCashBankIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/product-categories/': typeof AuthenticatedProductCategoriesIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/admin/account-categories/': typeof AuthenticatedAdminAccountCategoriesIndexRoute
  '/_authenticated/admin/menu-categories/': typeof AuthenticatedAdminMenuCategoriesIndexRoute
  '/_authenticated/admin/menus/': typeof AuthenticatedAdminMenusIndexRoute
  '/_authenticated/admin/permissions/': typeof AuthenticatedAdminPermissionsIndexRoute
  '/_authenticated/admin/plans/': typeof AuthenticatedAdminPlansIndexRoute
  '/_authenticated/admin/subscriptions/': typeof AuthenticatedAdminSubscriptionsIndexRoute
  '/_authenticated/admin/transaction-types/': typeof AuthenticatedAdminTransactionTypesIndexRoute
  '/_authenticated/expenses/add/': typeof AuthenticatedExpensesAddIndexRoute
  '/_authenticated/expenses/detail/': typeof AuthenticatedExpensesDetailIndexRoute
  '/_authenticated/expenses/edit/': typeof AuthenticatedExpensesEditIndexRoute
  '/_authenticated/products/add/': typeof AuthenticatedProductsAddIndexRoute
  '/_authenticated/products/edit/': typeof AuthenticatedProductsEditIndexRoute
  '/_authenticated/purchases/invoices/': typeof AuthenticatedPurchasesInvoicesIndexRoute
  '/_authenticated/purchases/overview/': typeof AuthenticatedPurchasesOverviewIndexRoute
  '/_authenticated/reports/balance-sheet/': typeof AuthenticatedReportsBalanceSheetIndexRoute
  '/_authenticated/reports/profit-loss/': typeof AuthenticatedReportsProfitLossIndexRoute
  '/_authenticated/sales/invoices/': typeof AuthenticatedSalesInvoicesIndexRoute
  '/_authenticated/sales/overview/': typeof AuthenticatedSalesOverviewIndexRoute
  '/_authenticated/settings/auto-sequencing/': typeof AuthenticatedSettingsAutoSequencingIndexRoute
  '/_authenticated/settings/company-roles/': typeof AuthenticatedSettingsCompanyRolesIndexRoute
  '/_authenticated/settings/company/': typeof AuthenticatedSettingsCompanyIndexRoute
  '/_authenticated/settings/payment-terms/': typeof AuthenticatedSettingsPaymentTermsIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/_authenticated/settings/subscription/': typeof AuthenticatedSettingsSubscriptionIndexRoute
  '/_authenticated/settings/tags/': typeof AuthenticatedSettingsTagsIndexRoute
  '/_authenticated/settings/taxes/': typeof AuthenticatedSettingsTaxesIndexRoute
  '/_authenticated/settings/units/': typeof AuthenticatedSettingsUnitsIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/_authenticated/purchases/invoices/add/': typeof AuthenticatedPurchasesInvoicesAddIndexRoute
  '/_authenticated/purchases/invoices/detail/': typeof AuthenticatedPurchasesInvoicesDetailIndexRoute
  '/_authenticated/purchases/invoices/edit/': typeof AuthenticatedPurchasesInvoicesEditIndexRoute
  '/_authenticated/sales/invoices/add/': typeof AuthenticatedSalesInvoicesAddIndexRoute
  '/_authenticated/sales/invoices/detail/': typeof AuthenticatedSalesInvoicesDetailIndexRoute
  '/_authenticated/sales/invoices/edit/': typeof AuthenticatedSalesInvoicesEditIndexRoute
  '/_authenticated/settings/company-roles/add/': typeof AuthenticatedSettingsCompanyRolesAddIndexRoute
  '/_authenticated/settings/company-roles/edit/': typeof AuthenticatedSettingsCompanyRolesEditIndexRoute
  '/_authenticated/admin/plans/$planId/permissions/': typeof AuthenticatedAdminPlansPlanIdPermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cash-bank/$accountName'
    | '/cash-bank/detail'
    | '/cash-bank/edit'
    | '/cash-bank/receive'
    | '/cash-bank/spend'
    | '/account'
    | '/cash-bank'
    | '/contacts'
    | '/expenses'
    | '/product-categories'
    | '/products'
    | '/reports'
    | '/settings'
    | '/admin/account-categories'
    | '/admin/menu-categories'
    | '/admin/menus'
    | '/admin/permissions'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/transaction-types'
    | '/expenses/add'
    | '/expenses/detail'
    | '/expenses/edit'
    | '/products/add'
    | '/products/edit'
    | '/purchases/invoices'
    | '/purchases/overview'
    | '/reports/balance-sheet'
    | '/reports/profit-loss'
    | '/sales/invoices'
    | '/sales/overview'
    | '/settings/auto-sequencing'
    | '/settings/company-roles'
    | '/settings/company'
    | '/settings/payment-terms'
    | '/settings/profile'
    | '/settings/subscription'
    | '/settings/tags'
    | '/settings/taxes'
    | '/settings/units'
    | '/settings/users'
    | '/purchases/invoices/add'
    | '/purchases/invoices/detail'
    | '/purchases/invoices/edit'
    | '/sales/invoices/add'
    | '/sales/invoices/detail'
    | '/sales/invoices/edit'
    | '/settings/company-roles/add'
    | '/settings/company-roles/edit'
    | '/admin/plans/$planId/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cash-bank/$accountName'
    | '/cash-bank/detail'
    | '/cash-bank/edit'
    | '/cash-bank/receive'
    | '/cash-bank/spend'
    | '/account'
    | '/cash-bank'
    | '/contacts'
    | '/expenses'
    | '/product-categories'
    | '/products'
    | '/reports'
    | '/settings'
    | '/admin/account-categories'
    | '/admin/menu-categories'
    | '/admin/menus'
    | '/admin/permissions'
    | '/admin/plans'
    | '/admin/subscriptions'
    | '/admin/transaction-types'
    | '/expenses/add'
    | '/expenses/detail'
    | '/expenses/edit'
    | '/products/add'
    | '/products/edit'
    | '/purchases/invoices'
    | '/purchases/overview'
    | '/reports/balance-sheet'
    | '/reports/profit-loss'
    | '/sales/invoices'
    | '/sales/overview'
    | '/settings/auto-sequencing'
    | '/settings/company-roles'
    | '/settings/company'
    | '/settings/payment-terms'
    | '/settings/profile'
    | '/settings/subscription'
    | '/settings/tags'
    | '/settings/taxes'
    | '/settings/units'
    | '/settings/users'
    | '/purchases/invoices/add'
    | '/purchases/invoices/detail'
    | '/purchases/invoices/edit'
    | '/sales/invoices/add'
    | '/sales/invoices/detail'
    | '/sales/invoices/edit'
    | '/settings/company-roles/add'
    | '/settings/company-roles/edit'
    | '/admin/plans/$planId/permissions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/cash-bank/$accountName'
    | '/_authenticated/cash-bank/detail'
    | '/_authenticated/cash-bank/edit'
    | '/_authenticated/cash-bank/receive'
    | '/_authenticated/cash-bank/spend'
    | '/_authenticated/account/'
    | '/_authenticated/cash-bank/'
    | '/_authenticated/contacts/'
    | '/_authenticated/expenses/'
    | '/_authenticated/product-categories/'
    | '/_authenticated/products/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/admin/account-categories/'
    | '/_authenticated/admin/menu-categories/'
    | '/_authenticated/admin/menus/'
    | '/_authenticated/admin/permissions/'
    | '/_authenticated/admin/plans/'
    | '/_authenticated/admin/subscriptions/'
    | '/_authenticated/admin/transaction-types/'
    | '/_authenticated/expenses/add/'
    | '/_authenticated/expenses/detail/'
    | '/_authenticated/expenses/edit/'
    | '/_authenticated/products/add/'
    | '/_authenticated/products/edit/'
    | '/_authenticated/purchases/invoices/'
    | '/_authenticated/purchases/overview/'
    | '/_authenticated/reports/balance-sheet/'
    | '/_authenticated/reports/profit-loss/'
    | '/_authenticated/sales/invoices/'
    | '/_authenticated/sales/overview/'
    | '/_authenticated/settings/auto-sequencing/'
    | '/_authenticated/settings/company-roles/'
    | '/_authenticated/settings/company/'
    | '/_authenticated/settings/payment-terms/'
    | '/_authenticated/settings/profile/'
    | '/_authenticated/settings/subscription/'
    | '/_authenticated/settings/tags/'
    | '/_authenticated/settings/taxes/'
    | '/_authenticated/settings/units/'
    | '/_authenticated/settings/users/'
    | '/_authenticated/purchases/invoices/add/'
    | '/_authenticated/purchases/invoices/detail/'
    | '/_authenticated/purchases/invoices/edit/'
    | '/_authenticated/sales/invoices/add/'
    | '/_authenticated/sales/invoices/detail/'
    | '/_authenticated/sales/invoices/edit/'
    | '/_authenticated/settings/company-roles/add/'
    | '/_authenticated/settings/company-roles/edit/'
    | '/_authenticated/admin/plans/$planId/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-categories/': {
      id: '/_authenticated/product-categories/'
      path: '/product-categories'
      fullPath: '/product-categories'
      preLoaderRoute: typeof AuthenticatedProductCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/': {
      id: '/_authenticated/cash-bank/'
      path: '/cash-bank'
      fullPath: '/cash-bank'
      preLoaderRoute: typeof AuthenticatedCashBankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/spend': {
      id: '/_authenticated/cash-bank/spend'
      path: '/cash-bank/spend'
      fullPath: '/cash-bank/spend'
      preLoaderRoute: typeof AuthenticatedCashBankSpendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/receive': {
      id: '/_authenticated/cash-bank/receive'
      path: '/cash-bank/receive'
      fullPath: '/cash-bank/receive'
      preLoaderRoute: typeof AuthenticatedCashBankReceiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/edit': {
      id: '/_authenticated/cash-bank/edit'
      path: '/cash-bank/edit'
      fullPath: '/cash-bank/edit'
      preLoaderRoute: typeof AuthenticatedCashBankEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/detail': {
      id: '/_authenticated/cash-bank/detail'
      path: '/cash-bank/detail'
      fullPath: '/cash-bank/detail'
      preLoaderRoute: typeof AuthenticatedCashBankDetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-bank/$accountName': {
      id: '/_authenticated/cash-bank/$accountName'
      path: '/cash-bank/$accountName'
      fullPath: '/cash-bank/$accountName'
      preLoaderRoute: typeof AuthenticatedCashBankAccountNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/units/': {
      id: '/_authenticated/settings/units/'
      path: '/settings/units'
      fullPath: '/settings/units'
      preLoaderRoute: typeof AuthenticatedSettingsUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/taxes/': {
      id: '/_authenticated/settings/taxes/'
      path: '/settings/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof AuthenticatedSettingsTaxesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/tags/': {
      id: '/_authenticated/settings/tags/'
      path: '/settings/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof AuthenticatedSettingsTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/subscription/': {
      id: '/_authenticated/settings/subscription/'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof AuthenticatedSettingsSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/payment-terms/': {
      id: '/_authenticated/settings/payment-terms/'
      path: '/settings/payment-terms'
      fullPath: '/settings/payment-terms'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentTermsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company/': {
      id: '/_authenticated/settings/company/'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company-roles/': {
      id: '/_authenticated/settings/company-roles/'
      path: '/settings/company-roles'
      fullPath: '/settings/company-roles'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/auto-sequencing/': {
      id: '/_authenticated/settings/auto-sequencing/'
      path: '/settings/auto-sequencing'
      fullPath: '/settings/auto-sequencing'
      preLoaderRoute: typeof AuthenticatedSettingsAutoSequencingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/overview/': {
      id: '/_authenticated/sales/overview/'
      path: '/sales/overview'
      fullPath: '/sales/overview'
      preLoaderRoute: typeof AuthenticatedSalesOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/invoices/': {
      id: '/_authenticated/sales/invoices/'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/profit-loss/': {
      id: '/_authenticated/reports/profit-loss/'
      path: '/reports/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof AuthenticatedReportsProfitLossIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/balance-sheet/': {
      id: '/_authenticated/reports/balance-sheet/'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AuthenticatedReportsBalanceSheetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/overview/': {
      id: '/_authenticated/purchases/overview/'
      path: '/purchases/overview'
      fullPath: '/purchases/overview'
      preLoaderRoute: typeof AuthenticatedPurchasesOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/invoices/': {
      id: '/_authenticated/purchases/invoices/'
      path: '/purchases/invoices'
      fullPath: '/purchases/invoices'
      preLoaderRoute: typeof AuthenticatedPurchasesInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/edit/': {
      id: '/_authenticated/products/edit/'
      path: '/products/edit'
      fullPath: '/products/edit'
      preLoaderRoute: typeof AuthenticatedProductsEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/add/': {
      id: '/_authenticated/products/add/'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof AuthenticatedProductsAddIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/edit/': {
      id: '/_authenticated/expenses/edit/'
      path: '/expenses/edit'
      fullPath: '/expenses/edit'
      preLoaderRoute: typeof AuthenticatedExpensesEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/detail/': {
      id: '/_authenticated/expenses/detail/'
      path: '/expenses/detail'
      fullPath: '/expenses/detail'
      preLoaderRoute: typeof AuthenticatedExpensesDetailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/add/': {
      id: '/_authenticated/expenses/add/'
      path: '/expenses/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof AuthenticatedExpensesAddIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/transaction-types/': {
      id: '/_authenticated/admin/transaction-types/'
      path: '/transaction-types'
      fullPath: '/admin/transaction-types'
      preLoaderRoute: typeof AuthenticatedAdminTransactionTypesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscriptions/': {
      id: '/_authenticated/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans/': {
      id: '/_authenticated/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions/': {
      id: '/_authenticated/admin/permissions/'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/menus/': {
      id: '/_authenticated/admin/menus/'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AuthenticatedAdminMenusIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/menu-categories/': {
      id: '/_authenticated/admin/menu-categories/'
      path: '/menu-categories'
      fullPath: '/admin/menu-categories'
      preLoaderRoute: typeof AuthenticatedAdminMenuCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/account-categories/': {
      id: '/_authenticated/admin/account-categories/'
      path: '/account-categories'
      fullPath: '/admin/account-categories'
      preLoaderRoute: typeof AuthenticatedAdminAccountCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/settings/company-roles/edit/': {
      id: '/_authenticated/settings/company-roles/edit/'
      path: '/settings/company-roles/edit'
      fullPath: '/settings/company-roles/edit'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRolesEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company-roles/add/': {
      id: '/_authenticated/settings/company-roles/add/'
      path: '/settings/company-roles/add'
      fullPath: '/settings/company-roles/add'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRolesAddIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/invoices/edit/': {
      id: '/_authenticated/sales/invoices/edit/'
      path: '/sales/invoices/edit'
      fullPath: '/sales/invoices/edit'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/invoices/detail/': {
      id: '/_authenticated/sales/invoices/detail/'
      path: '/sales/invoices/detail'
      fullPath: '/sales/invoices/detail'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesDetailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/invoices/add/': {
      id: '/_authenticated/sales/invoices/add/'
      path: '/sales/invoices/add'
      fullPath: '/sales/invoices/add'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesAddIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/invoices/edit/': {
      id: '/_authenticated/purchases/invoices/edit/'
      path: '/purchases/invoices/edit'
      fullPath: '/purchases/invoices/edit'
      preLoaderRoute: typeof AuthenticatedPurchasesInvoicesEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/invoices/detail/': {
      id: '/_authenticated/purchases/invoices/detail/'
      path: '/purchases/invoices/detail'
      fullPath: '/purchases/invoices/detail'
      preLoaderRoute: typeof AuthenticatedPurchasesInvoicesDetailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/invoices/add/': {
      id: '/_authenticated/purchases/invoices/add/'
      path: '/purchases/invoices/add'
      fullPath: '/purchases/invoices/add'
      preLoaderRoute: typeof AuthenticatedPurchasesInvoicesAddIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/plans/$planId/permissions/': {
      id: '/_authenticated/admin/plans/$planId/permissions/'
      path: '/plans/$planId/permissions'
      fullPath: '/admin/plans/$planId/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPlansPlanIdPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountCategoriesIndexRoute: typeof AuthenticatedAdminAccountCategoriesIndexRoute
  AuthenticatedAdminMenuCategoriesIndexRoute: typeof AuthenticatedAdminMenuCategoriesIndexRoute
  AuthenticatedAdminMenusIndexRoute: typeof AuthenticatedAdminMenusIndexRoute
  AuthenticatedAdminPermissionsIndexRoute: typeof AuthenticatedAdminPermissionsIndexRoute
  AuthenticatedAdminPlansIndexRoute: typeof AuthenticatedAdminPlansIndexRoute
  AuthenticatedAdminSubscriptionsIndexRoute: typeof AuthenticatedAdminSubscriptionsIndexRoute
  AuthenticatedAdminTransactionTypesIndexRoute: typeof AuthenticatedAdminTransactionTypesIndexRoute
  AuthenticatedAdminPlansPlanIdPermissionsIndexRoute: typeof AuthenticatedAdminPlansPlanIdPermissionsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountCategoriesIndexRoute:
      AuthenticatedAdminAccountCategoriesIndexRoute,
    AuthenticatedAdminMenuCategoriesIndexRoute:
      AuthenticatedAdminMenuCategoriesIndexRoute,
    AuthenticatedAdminMenusIndexRoute: AuthenticatedAdminMenusIndexRoute,
    AuthenticatedAdminPermissionsIndexRoute:
      AuthenticatedAdminPermissionsIndexRoute,
    AuthenticatedAdminPlansIndexRoute: AuthenticatedAdminPlansIndexRoute,
    AuthenticatedAdminSubscriptionsIndexRoute:
      AuthenticatedAdminSubscriptionsIndexRoute,
    AuthenticatedAdminTransactionTypesIndexRoute:
      AuthenticatedAdminTransactionTypesIndexRoute,
    AuthenticatedAdminPlansPlanIdPermissionsIndexRoute:
      AuthenticatedAdminPlansPlanIdPermissionsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCashBankAccountNameRoute: typeof AuthenticatedCashBankAccountNameRoute
  AuthenticatedCashBankDetailRoute: typeof AuthenticatedCashBankDetailRoute
  AuthenticatedCashBankEditRoute: typeof AuthenticatedCashBankEditRoute
  AuthenticatedCashBankReceiveRoute: typeof AuthenticatedCashBankReceiveRoute
  AuthenticatedCashBankSpendRoute: typeof AuthenticatedCashBankSpendRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedCashBankIndexRoute: typeof AuthenticatedCashBankIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedProductCategoriesIndexRoute: typeof AuthenticatedProductCategoriesIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedExpensesAddIndexRoute: typeof AuthenticatedExpensesAddIndexRoute
  AuthenticatedExpensesDetailIndexRoute: typeof AuthenticatedExpensesDetailIndexRoute
  AuthenticatedExpensesEditIndexRoute: typeof AuthenticatedExpensesEditIndexRoute
  AuthenticatedProductsAddIndexRoute: typeof AuthenticatedProductsAddIndexRoute
  AuthenticatedProductsEditIndexRoute: typeof AuthenticatedProductsEditIndexRoute
  AuthenticatedPurchasesInvoicesIndexRoute: typeof AuthenticatedPurchasesInvoicesIndexRoute
  AuthenticatedPurchasesOverviewIndexRoute: typeof AuthenticatedPurchasesOverviewIndexRoute
  AuthenticatedReportsBalanceSheetIndexRoute: typeof AuthenticatedReportsBalanceSheetIndexRoute
  AuthenticatedReportsProfitLossIndexRoute: typeof AuthenticatedReportsProfitLossIndexRoute
  AuthenticatedSalesInvoicesIndexRoute: typeof AuthenticatedSalesInvoicesIndexRoute
  AuthenticatedSalesOverviewIndexRoute: typeof AuthenticatedSalesOverviewIndexRoute
  AuthenticatedSettingsAutoSequencingIndexRoute: typeof AuthenticatedSettingsAutoSequencingIndexRoute
  AuthenticatedSettingsCompanyRolesIndexRoute: typeof AuthenticatedSettingsCompanyRolesIndexRoute
  AuthenticatedSettingsCompanyIndexRoute: typeof AuthenticatedSettingsCompanyIndexRoute
  AuthenticatedSettingsPaymentTermsIndexRoute: typeof AuthenticatedSettingsPaymentTermsIndexRoute
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
  AuthenticatedSettingsSubscriptionIndexRoute: typeof AuthenticatedSettingsSubscriptionIndexRoute
  AuthenticatedSettingsTagsIndexRoute: typeof AuthenticatedSettingsTagsIndexRoute
  AuthenticatedSettingsTaxesIndexRoute: typeof AuthenticatedSettingsTaxesIndexRoute
  AuthenticatedSettingsUnitsIndexRoute: typeof AuthenticatedSettingsUnitsIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
  AuthenticatedPurchasesInvoicesAddIndexRoute: typeof AuthenticatedPurchasesInvoicesAddIndexRoute
  AuthenticatedPurchasesInvoicesDetailIndexRoute: typeof AuthenticatedPurchasesInvoicesDetailIndexRoute
  AuthenticatedPurchasesInvoicesEditIndexRoute: typeof AuthenticatedPurchasesInvoicesEditIndexRoute
  AuthenticatedSalesInvoicesAddIndexRoute: typeof AuthenticatedSalesInvoicesAddIndexRoute
  AuthenticatedSalesInvoicesDetailIndexRoute: typeof AuthenticatedSalesInvoicesDetailIndexRoute
  AuthenticatedSalesInvoicesEditIndexRoute: typeof AuthenticatedSalesInvoicesEditIndexRoute
  AuthenticatedSettingsCompanyRolesAddIndexRoute: typeof AuthenticatedSettingsCompanyRolesAddIndexRoute
  AuthenticatedSettingsCompanyRolesEditIndexRoute: typeof AuthenticatedSettingsCompanyRolesEditIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCashBankAccountNameRoute: AuthenticatedCashBankAccountNameRoute,
  AuthenticatedCashBankDetailRoute: AuthenticatedCashBankDetailRoute,
  AuthenticatedCashBankEditRoute: AuthenticatedCashBankEditRoute,
  AuthenticatedCashBankReceiveRoute: AuthenticatedCashBankReceiveRoute,
  AuthenticatedCashBankSpendRoute: AuthenticatedCashBankSpendRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedCashBankIndexRoute: AuthenticatedCashBankIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedProductCategoriesIndexRoute:
    AuthenticatedProductCategoriesIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedExpensesAddIndexRoute: AuthenticatedExpensesAddIndexRoute,
  AuthenticatedExpensesDetailIndexRoute: AuthenticatedExpensesDetailIndexRoute,
  AuthenticatedExpensesEditIndexRoute: AuthenticatedExpensesEditIndexRoute,
  AuthenticatedProductsAddIndexRoute: AuthenticatedProductsAddIndexRoute,
  AuthenticatedProductsEditIndexRoute: AuthenticatedProductsEditIndexRoute,
  AuthenticatedPurchasesInvoicesIndexRoute:
    AuthenticatedPurchasesInvoicesIndexRoute,
  AuthenticatedPurchasesOverviewIndexRoute:
    AuthenticatedPurchasesOverviewIndexRoute,
  AuthenticatedReportsBalanceSheetIndexRoute:
    AuthenticatedReportsBalanceSheetIndexRoute,
  AuthenticatedReportsProfitLossIndexRoute:
    AuthenticatedReportsProfitLossIndexRoute,
  AuthenticatedSalesInvoicesIndexRoute: AuthenticatedSalesInvoicesIndexRoute,
  AuthenticatedSalesOverviewIndexRoute: AuthenticatedSalesOverviewIndexRoute,
  AuthenticatedSettingsAutoSequencingIndexRoute:
    AuthenticatedSettingsAutoSequencingIndexRoute,
  AuthenticatedSettingsCompanyRolesIndexRoute:
    AuthenticatedSettingsCompanyRolesIndexRoute,
  AuthenticatedSettingsCompanyIndexRoute:
    AuthenticatedSettingsCompanyIndexRoute,
  AuthenticatedSettingsPaymentTermsIndexRoute:
    AuthenticatedSettingsPaymentTermsIndexRoute,
  AuthenticatedSettingsProfileIndexRoute:
    AuthenticatedSettingsProfileIndexRoute,
  AuthenticatedSettingsSubscriptionIndexRoute:
    AuthenticatedSettingsSubscriptionIndexRoute,
  AuthenticatedSettingsTagsIndexRoute: AuthenticatedSettingsTagsIndexRoute,
  AuthenticatedSettingsTaxesIndexRoute: AuthenticatedSettingsTaxesIndexRoute,
  AuthenticatedSettingsUnitsIndexRoute: AuthenticatedSettingsUnitsIndexRoute,
  AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  AuthenticatedPurchasesInvoicesAddIndexRoute:
    AuthenticatedPurchasesInvoicesAddIndexRoute,
  AuthenticatedPurchasesInvoicesDetailIndexRoute:
    AuthenticatedPurchasesInvoicesDetailIndexRoute,
  AuthenticatedPurchasesInvoicesEditIndexRoute:
    AuthenticatedPurchasesInvoicesEditIndexRoute,
  AuthenticatedSalesInvoicesAddIndexRoute:
    AuthenticatedSalesInvoicesAddIndexRoute,
  AuthenticatedSalesInvoicesDetailIndexRoute:
    AuthenticatedSalesInvoicesDetailIndexRoute,
  AuthenticatedSalesInvoicesEditIndexRoute:
    AuthenticatedSalesInvoicesEditIndexRoute,
  AuthenticatedSettingsCompanyRolesAddIndexRoute:
    AuthenticatedSettingsCompanyRolesAddIndexRoute,
  AuthenticatedSettingsCompanyRolesEditIndexRoute:
    AuthenticatedSettingsCompanyRolesEditIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
